### PR TITLE
Resolves #186 - MobileServiceContractResolver is now threadsafe.

### LINKED ISSUE #186: Investigate threading issues with MobileServiceContractResolver
There seems to be a race condition involving the singleton MobileServiceContractResolver. See for instance http://stackoverflow.com/questions/38441850/issue-making-calls-with-azure-mobile-client-in-parallel-with-task-whenall/38442520.

Potential workaround is to issue one request to a table and await it, so that the MobileServiceContractResolver object is created for the table. Then, future requests should reused the previously created resolver.

Symptom is stack traces like the following:

> Collection was modified; enumeration operation may not execute.
> at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
> at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
> at Microsoft.WindowsAzure.MobileServices.MobileServiceContractResolver.CreateProperties(Type type, MemberSerialization memberSerialization)
> at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
> at Microsoft.WindowsAzure.MobileServices.MobileServiceContractResolver.CreateObjectContract(Type type)
> at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
> at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
> at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
> at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
> at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
> at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
> at Microsoft.WindowsAzure.MobileServices.MobileServiceSerializer.<>c__DisplayClass35_0`1.<Deserialize>b__0()
> at Microsoft.WindowsAzure.MobileServices.MobileServiceSerializer.TransformSerializationException[T](Action action, JToken token)
> at Microsoft.WindowsAzure.MobileServices.MobileServiceSerializer.Deserialize[T](JToken json, JsonSerializer jsonSerializer)
> at Microsoft.WindowsAzure.MobileServices.MobileServiceSerializer.Deserialize[T](JToken json)
> at Microsoft.WindowsAzure.MobileServices.MobileServiceTable`1.<LookupAsync>d__14.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---

### PR DESCRIPTION
**Pull request by paulbatum**
All the thread safety issues appear to be around the jsonPropertyCache, so I just serialized the writes to the cache and made sure that enumeration was done from a copy. Considering we're already in edge case land I did not go as far as comparing the JsonContract instances returned because there is no convenient equals operation to piggy back onto. But I did inspect the code path and I'm reasonably confident that two racing ResolveContract(..) calls are idempotent.

### CODE REVIEW

**Comment by paulbatum** [comment]
@fabiocav @pragnagopa can you guys take a quick look at this?

File: src/Microsoft.WindowsAzure.MobileServices/Table/Serialization/MobileServiceContractResolver.cs [hunk 1]
```diff
@@ -321,7 +321,11 @@ protected override JsonObjectContract CreateObjectContract(Type type)
         protected override JsonProperty CreateProperty(MemberInfo member, MemberSerialization memberSerialization)
         {
             JsonProperty property = base.CreateProperty(member, memberSerialization);
-            this.jsonPropertyCache[member] = property;
+
+            lock (jsonPropertyCache)
```
Comment (fabiocav) [inline src/Microsoft.WindowsAzure.MobileServices/Table/Serialization/MobileServiceContractResolver.cs]: Should we use a reader/writer lock? There's still a (now reduced) possibility that this will be iterating the collection to create the list while `CreateProperty` has acquired the lock and is modifying the collection.

File: unittest/Microsoft.WindowsAzure.MobileServices.Test.Unit/Table/MobileServiceContractResolverTests.cs [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+            const int iterationCount = 100;
+
+            for (int i = 0; i < iterationCount; i++)
+            {
+                MobileServiceContractResolver contractResolver = new MobileServiceContractResolver();
+                Func<JsonContract> resolveContract = () => contractResolver.ResolveContract(typeof(PocoType));
+                
+                Task t1 = Task.Run(resolveContract);
+                Task t2 = Task.Run(resolveContract);                
+                Task.WhenAll(t1, t2).Wait();
```
Comment (fabiocav) [inline unittest/Microsoft.WindowsAzure.MobileServices.Test.Unit/Table/MobileServiceContractResolverTests.cs]: Might be worth having `resolveContract` wait on a semaphore (SemaphoreSlim) and signal that semaphore once your tasks are setup and signal a countdown event.

Comment (shrishrirang) [inline unittest/Microsoft.WindowsAzure.MobileServices.Test.Unit/Table/MobileServiceContractResolverTests.cs]: Because t1 and t2 are short lived tasks, creating them just once and calling `ResolveContract()` 100 times within each of those will have a higher chance of simulating concurrent execution than creating t1 and t2 100 times and calling `ResolveContract()` just once.

**Comment by fabiocav** [comment]
:shipit:

File: unittest/Microsoft.WindowsAzure.MobileServices.Test.Unit/Table/MobileServiceContractResolverTests.cs (hunk 2 above)
Comment (paulbatum) [inline unittest/Microsoft.WindowsAzure.MobileServices.Test.Unit/Table/MobileServiceContractResolverTests.cs]: @shrishrirang I tested this quickly and found it to be worse. My current version of the test fails reliably while if I move the loop inside the task, it fails only about 50% of the time (both based on 100 iterations). I suspect this is due to some amount of caching logic that is inside the contract resolver. That caching logic is avoided if you make a new instance of the resolver per iteration.

**Comment by paulbatum** [comment]
There are still more thread safety problems so this PR isn't ready to merge yet.

**Comment by paulbatum** [comment]
OK I have verified that this latest version runs successfully using the repro supplied in the [stack overflow post](http://stackoverflow.com/questions/38441850/issue-making-calls-with-azure-mobile-client-in-parallel-with-task-whenall/38442520).

**Comment by paulbatum** [comment]
It appears I got confused about ConcurrentDictionary's availability on WP8.. it seems to be supported. Will update again with a simpler fix.

**Comment by paulbatum** [comment]
Spoke too soon.. I think I was right the first time. No concurrent dictionary so my current implementation stands.

**Comment by fabiocav** [comment]
:shipit:
